### ISSUE TITLE
Smarter number format detection

### ISSUE THREAD

**Issue by kwkroll32** [tahatopiwala/QuaCRS#2]
Near line 25 in compare_detail_view.php, there is a long if/else statement that detects what format to use when printing numbers. Somehow, the string variables in my "general" table are being forced through this function, mutilating the values and throwing an ugly warning. Unique ID should be the sample name, not an int. I have no clue where that integer value is coming from.
![issue2](https://cloud.githubusercontent.com/assets/8041208/11665643/7ce038fc-9db6-11e5-9e02-e36cce4e291c.PNG)

**Comment by tahatopiwala** [comment]
Hi Karl,

That is a database error because of the case sensitivity. To have that error vanish please follow these steps and make changes to ->> Application / Models / Sample_model / Line number 153. The word general show be switched to General.

Best,
Taha

**Comment by kwkroll32** [comment]
That resolved the particular issue. Perhaps we should change all instances of lowercase "general" to capital "General", since QuaCRS2 will likely ship in that configuration. 

Alternatively, I could change the script that makes the database, so that the table is created as lowercase. It used to be capitalized to insure that it appeared at the top of a sample's results page, but I'm not sure if this is still necessary.
