### ISSUE TITLE
Decimals being cast as int? 

### ISSUE THREAD

**Issue by kwkroll32** [tahatopiwala/QuaCRS#3]
Duplication rate (and possibly other rates - data not shown) appears to be cast as an int on the front page. Duplication rate is defined as a decimal in the XML and stored as such in the database. Is there a way to preserve the precision in the database for a numerical metric? That is, if duplication rate has 8 decimal places in the database, can the displayed value have the same number of decimal places? 
![issue3](https://cloud.githubusercontent.com/assets/8041208/11666338/ff365388-9db9-11e5-9758-3eed7b130e46.PNG)

**Comment by tahatopiwala** [comment]
By default even my copy of QuaCRS does not give decimal notation. I will check what the issue is and let you know
