### ISSUE TITLE
Select All button

### ISSUE THREAD

**Issue by kwkroll32** [tahatopiwala/QuaCRS#5]
I propose that clicking "Select" [the top of the column that holds all radio buttons] will select all the visible radio buttons. I imagine this would be very useful combined with search, where I could search for "Study1", select all the study1 samples with a single click, and allocate them to a group. Then, I'd want to clear that search, submit a new search, and do the same thing to make a new group for "Study2". That would save a lot of time if study1 and study2 have too many samples to click them all individually. 
![issue5](https://cloud.githubusercontent.com/assets/8041208/11666699/d14b5188-9dbb-11e5-9f58-ae439b02edea.PNG)

**Comment by tahatopiwala** [comment]
Yes that makes more sense and a better thing to do. I will apply that to the code.

**Comment by kwkroll32** [comment]
Select All seems to be broken for me. 
1. not sure if it's designed this way, but select all doesn't do anything unless I have a search implemented.
2. clicking on select all will permanently select a sample. Ex:
2a) Click select all and add to group --> group gets all samples [expected] 
2b) Click select all, deselect a sample with 1 click --> group gets all samples, and the "deselected" one still has it's radio filled. 
2c) Click select all, deselect a sample with 2 clicks --> group gets all samples, and the "deselected" one has an empty radio button.
2d) Click select all, deselect a sample with 2 clicks, then select it again --> group gets all samples, plus a duplicate of the deselected/reselected sample. 
![issue5 2](https://cloud.githubusercontent.com/assets/8041208/11717848/edab95d4-9f20-11e5-9ba2-d799a94c91e2.PNG)

**Comment by kwkroll32** [comment]
Also, can you rename the column to say "Select All"? Ralf said it is not clear that's what the button does, just from looking at it.
